// constants.js
export const carouselItems = [
  {
    id: 1,
    image:
      "https://indiathrills.com/wp-content/uploads/2022/07/8565363673_50bfe4fbae_b.jpg",
    title: "Auli",
    description: "Distance from Delhi: Approximately 500 km",
    extraDescription: "Auli is known for its stunning skiing slopes and scenic views.",
    location: "Auli, Uttarakhand, India",
  },
  {
    id: 2,
    image:
      "https://yhaindia.org/UploadsProgramImages/gallery_919/ChoptaDP-6.jpg",
    title: "Tungnath",
    description: "Distance from Delhi: Approximately 400 km",
    extraDescription: "Tungnath is a beautiful temple located at the highest altitude of any Shiva temple in India.",
    location: "Tungnath, Uttarakhand, India",
  },
  {
    id: 3,
    image:
      "https://www.taxiservicedehradun.com/image/rishikesh-to-badrinath-tempo-traveller.webp",
    title: "Badrinath",
    description: "Distance from Delhi: Approximately 540 km",
    extraDescription: "Badrinath is one of the Char Dham pilgrimage sites in Uttarakhand, attracting thousands of devotees each year.",
    location: "Badrinath, Uttarakhand, India",
  },
  {
    id: 4,
    image: "https://link_to_kartik_swami_image.com",
    title: "Kartik Swami Temple",
    description: "Distance from Delhi: Approximately 450 km",
    extraDescription: "Kartik Swami Temple is situated in the Garhwal region of Uttarakhand.",
    location: "Kartik Swami Temple, Uttarakhand, India",
  },
  {
    id: 5,
    image: "https://link_to_madmaheshwar_image.com",
    title: "Shri Madmaheshwar Temple",
    description: "Distance from Delhi: Approximately 470 km",
    extraDescription: "Shri Madmaheshwar Temple is one of the Panch Kedar temples in Uttarakhand.",
    location: "Shri Madmaheshwar Temple, Uttarakhand, India",
  },
  {
    id: 6,
    image: "https://link_to_hemkund_sahib_image.com",
    title: "Hemkund Sahib",
    description: "Distance from Delhi: Approximately 550 km",
    extraDescription: "Hemkund Sahib is a revered Sikh pilgrimage site in the Himalayas.",
    location: "Hemkund Sahib, Uttarakhand, India",
  },
  {
    id: 7,
    image: "https://link_to_deoria_taal_image.com",
    title: "Deoria Taal",
    description: "Distance from Delhi: Approximately 400 km",
    extraDescription: "Deoria Taal is a picturesque lake located in the Garhwal region.",
    location: "Deoria Taal, Uttarakhand, India",
  },
  {
    id: 8,
    image: "https://link_to_roopkund_image.com",
    title: "Roopkund (Lohajung Pass)",
    description: "Distance from Delhi: Approximately 500 km",
    extraDescription: "Roopkund is famous for its mysterious skeleton lake and scenic trekking routes.",
    location: "Roopkund, Uttarakhand, India",
  },
  {
    id: 9,
    image: "https://link_to_valley_of_flowers_image.com",
    title: "Valley of Flowers",
    description: "Distance from Delhi: Approximately 500 km",
    extraDescription: "The Valley of Flowers is a UNESCO World Heritage site known for its diverse alpine flora.",
    location: "Valley of Flowers, Uttarakhand, India",
  },
  {
    id: 10,
    image: "https://link_to_kedarnath_image.com",
    title: "Kedarnath Temple",
    description: "Distance from Delhi: Approximately 600 km",
    extraDescription: "Kedarnath Temple is one of the Char Dham pilgrimage sites and one of the holiest temples in India.",
    location: "Kedarnath Temple, Uttarakhand, India",
  },
  {
    id: 11,
    image: "https://link_to_vasudhara_falls_image.com",
    title: "Vasudhara Falls",
    description: "Distance from Delhi: Approximately 550 km",
    extraDescription: "Vasudhara Falls is a scenic waterfall located in the Kedarnath region of Uttarakhand.",
    location: "Vasudhara Falls, Uttarakhand, India",
  },
  {
    id: 12,
    image: "https://link_to_adibadri_temple_image.com",
    title: "Adibadri Temple",
    description: "Distance from Delhi: Approximately 450 km",
    extraDescription: "Adibadri Temple is one of the lesser-known temples in Uttarakhand, surrounded by beautiful hills.",
    location: "Adibadri Temple, Uttarakhand, India",
  },
  {
    id: 13,
    image: "https://link_to_karanprayag_sangam_image.com",
    title: "Karanprayag Sangam",
    description: "Distance from Delhi: Approximately 450 km",
    extraDescription: "Karanprayag is the confluence of the Alaknanda and Pindar rivers, and a sacred spot in Uttarakhand.",
    location: "Karanprayag Sangam, Uttarakhand, India",
  },
  {
    id: 14,
    image: "https://link_to_karna_temple_image.com",
    title: "Karna Temple",
    description: "Distance from Delhi: Approximately 500 km",
    extraDescription: "Karna Temple is dedicated to the great warrior Karna from the Mahabharata.",
    location: "Karna Temple, Uttarakhand, India",
  },
  {
    id: 15,
    image: "https://link_to_benital_image.com",
    title: "Benital",
    description: "Distance from Delhi: Approximately 400 km",
    extraDescription: "Benital is a scenic location with natural beauty and serene surroundings.",
    location: "Benital, Uttarakhand, India",
  },
  {
    id: 16,
    image: "https://link_to_rudranath_temple_image.com",
    title: "Rudranath Temple (Sagar Village)",
    description: "Distance from Delhi: Approximately 450 km",
    extraDescription: "Rudranath Temple is one of the Panch Kedar temples and is located at an altitude of 2,100 meters.",
    location: "Rudranath Temple, Uttarakhand, India",
  },
  {
    id: 17,
    image: "https://link_to_dhari_devi_temple_image.com",
    title: "Dhari Devi Temple",
    description: "Distance from Delhi: Approximately 450 km",
    extraDescription: "Dhari Devi Temple is dedicated to the goddess Dhari Devi, located near Srinagar in Uttarakhand.",
    location: "Dhari Devi Temple, Uttarakhand, India",
  },
  {
    id: 18,
    image: "https://link_to_triyuginarayan_temple_image.com",
    title: "Triyuginarayan Temple",
    description: "Distance from Delhi: Approximately 500 km",
    extraDescription: "Triyuginarayan Temple is known for its association with the wedding of Lord Shiva and Parvati.",
    location: "Triyuginarayan Temple, Uttarakhand, India",
  },
];
