name: Ping GeetaHomestay

on:
  schedule:
    - cron: "*/9 * * * *"  # Every 9 minutes
  workflow_dispatch:       # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Random delay (0–180 seconds)
        run: |
          DELAY=$(( RANDOM % 181 ))
          echo "Sleeping for $DELAY seconds to randomize ping interval."
          sleep $DELAY

      - name: Ping status route
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://geetahomestay.onrender.com/status
